### ISSUE TITLE
Support Groonga 5.0.2

### ISSUE THREAD

**Issue by myokoym** [ranguba/rroonga#57]
Rroonga 5.0.1のリリース #56 に向けて、3/31にリリースされたGroonga 5.0.2に対応する。
まずは必要な作業をこのissueにリストアップして、その後でそれぞれに対してpull requestを作成する。

* [x] [rroonga-build.rb](https://github.com/ranguba/rroonga/blob/master/rroonga-build.rb)の`RequiredGroongaVersion`を5.0.2に上げる
* [x] `GRN_SCORER_ERROR`の追加に対応する。
* [x] `grn_expr_estimate_size()`の存在チェックを削除する。
* [x] `grn_column_index()`が非推奨になったので`grn_column_find_index_data()`に置き換える。
* [ ] Database#tablesを`grn_ctx_get_all_tables()`を使った実装に置き換える。
* [ ] スコア関数をRroongaから使えるようにする :scorer => :tf_idfとか今後スコア関数が増えてもいいように。
* [x] #60 正規表現がらみでTokenRegexも受け付けるようにする。(ただし粒度が大きいので以下に分離)
  * #61 スキーマ定義でTokenRegexを指定できるようにする作業
  * #62 前方一致検索できるようにする作業 (これも大きいので分離する)
     * #63 Groongaでの使い方を知る
     * #64 Rroongaでのselectの挙動を知る
     * #65 GroongaとRroongaをつなぐ (実装に必要なパーツを揃える)
     * #66 Table#selectで文字列で前方一致のメタ文字（\A）を実装(まずは文字列を受け付けるようにするところから)
     * #67 Table#selectでRegexp型を受け入れ(よりRubyらしく検索できるように)
     * #70 Table#selectでRegexp型で前方一致のメタ文字（\A）を実装
  * #68 TokenRegexpで後方一致検索 (大きいので分離)
     * #69  Table#selectで文字列で後方一致のメタ文字（\z）を実装
     * #71 Table#selectでRegexp型で後方一致のメタ文字（\z）を実装
* [x] pluginを登録解除できるようにする。
* [x] Bind grn_operator_exec_match() #80
* [x] Bind grn_operator_exec_prefix() #81
* [x] Bind grn_operator_exec_regexp() #82

**Comment by kenhys** [comment]
非互換な変更について。
grn_search_optargについては以下のように対応済み。

./ext/groonga/rb-grn-index-column.c:    grn_search_optarg options;
./ext/groonga/rb-grn-index-column.c:    memset(&options, 0, sizeof(grn_search_optarg));
./ext/groonga/rb-grn-double-array-trie.c:    grn_search_optarg search_options;
./ext/groonga/rb-grn-double-array-trie.c:    memset(&search_options, 0, sizeof(grn_search_optarg));
./ext/groonga/rb-grn-patricia-trie.c:    grn_search_optarg search_options;
./ext/groonga/rb-grn-patricia-trie.c:    memset(&search_options, 0, sizeof(grn_search_optarg));

**Comment by kenhys** [comment]
_scoreの内部的な型変更による影響についてはext側をみるになさそうだ。

**Comment by kenhys** [comment]
http://groonga.org/docs/reference/api/grn_ctx.html#c.grn_ctx_get_all_tables
既存の機能で@database.tablesが実装されているので、テーブルをごっそり取得するというのはできている。

**Comment by myokoym** [comment]
`GRN_SCORER_ERROR`の追加に対応する。

```
rb-grn-exception.c: In function ‘rb_grn_rc_to_exception’:
rb-grn-exception.c:108:5: warning: enumeration value ‘GRN_SCORER_ERROR’ not handled in switch [-Wswitch]
     switch (rc) {
     ^
rb-grn-exception.c: In function ‘rb_grn_rc_to_message’:
rb-grn-exception.c:353:5: warning: enumeration value ‘GRN_SCORER_ERROR’ not handled in switch [-Wswitch]
     switch (rc) {
     ^
```

参考:  commit d81abfe2f3dda9f104f6b392e3e857d86f02c09a

**Comment by kenhys** [comment]
スコア関数をRroongaから使えるようにする :scorer => :tf_idfとか今後スコア関数が増えてもいいように。
http://groonga.org/docs/reference/scorer.html

**Comment by myokoym** [comment]
[rroonga-build.rb](https://github.com/ranguba/rroonga/blob/master/rroonga-build.rb)の`RequiredGroongaVersion`を5.0.2に上げる。

**Comment by myokoym** [comment]
`grn_expr_estimate_size` の存在チェックを削除する。
参考:  commit 51350ef85630a5e045e07ada3b19e5ff9586fa00

**Comment by kenhys** [comment]
正規表現がらみでTokenRegexも受け付けるようにする。

**Comment by kenhys** [comment]
pluginを登録解除できるようにする。
http://groonga.org/docs/reference/commands/plugin_unregister.html

**Comment by myokoym** [comment]
Groongaを更新したことによるビルド時の警告と、5.0.1関係のTODOコメントは確認完了しました。

**Comment by myokoym** [comment]
`grn_column_index()`が非推奨になったので`grn_column_find_index_data()`に置き換える。

**Comment by myokoym** [comment]
一番上にリストアップしました。
スコア関数や正規表現は粒度が大きいので、もう少し細かくしてから作業を始めます。

**Comment by kenhys** [comment]
コミットできるかRequiredGroongaVersionを上げてみる。

**Comment by kenhys** [comment]
軽めのものから順番に作業していくことにした。
* GRN_SCORER_ERRORの追加に対応する。
* pluginを登録解除できるようにする
* grn_column_index()が非推奨になったのでgrn_column_find_index_data()に置き換える。

**Comment by kenhys** [comment]
全部のログはとってなかったけど、rake build:windowsで手元のunstableだとこけていたのでメモ。

```
==> default: cd -
==> default: mkdir -p tmp/x64-mingw32/stage/lib/2.1
==> default: install -c tmp/x64-mingw32/groonga/2.1.5/groonga.so lib/2.1/groonga.so
==> default: cp tmp/x64-mingw32/groonga/2.1.5/groonga.so tmp/x64-mingw32/stage/lib/2.1/groonga.so
==> default: mkdir -p tmp/x64-mingw32/groonga/2.2.1
==> default: cp /home/vagrant/.rake-compiler/ruby/x86_64-w64-mingw32/ruby-2.2.1/lib/ruby/2.2.0/mkmf.rb tmp/x64-mingw32/groonga/2.2.1/mkmf.rb
==> default: cd tmp/x64-mingw32/groonga/2.2.1
==> default: /home/vagrant/.rbenv/versions/1.9.3-p551/bin/ruby -I. ../../../../ext/groonga/extconf.rb
==> default: /home/vagrant/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/bundler-1.9.2/lib/bundler/spec_set.rb:92:in `block in materialize': Could not find RedCloth-4.2.9 in any of the sources (Bundler::GemNotFound)
==> default:    from /home/vagrant/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/bundler-1.9.2/lib/bundler/spec_set.rb:85:in `map!'
==> default:    from /home/vagrant/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/bundler-1.9.2/lib/bundler/spec_set.rb:85:in `materialize'
==> default:    from /home/vagrant/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/bundler-1.9.2/lib/bundler/definition.rb:132:in `specs'
==> default:    from /home/vagrant/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/bundler-1.9.2/lib/bundler/definition.rb:177:in `specs_for'
==> default:    from /home/vagrant/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/bundler-1.9.2/lib/bundler/definition.rb:166:in `requested_specs'
==> default:    from /home/vagrant/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/bundler-1.9.2/lib/bundler/environment.rb:18:in `requested_specs'
==> default:    from /home/vagrant/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/bundler-1.9.2/lib/bundler/runtime.rb:13:in `setup'
==> default:    from /home/vagrant/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/bundler-1.9.2/lib/bundler.rb:122:in `setup'
==> default:    from /home/vagrant/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/bundler-1.9.2/lib/bundler/setup.rb:18:in `<top (required)>'
==> default:    from /home/vagrant/.rbenv/versions/1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54:in `require'
==> default:    from /home/vagrant/.rbenv/versions/1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54:in `require'
==> default: rake aborted!
==> default: Command failed with status (1): [/home/vagrant/.rbenv/versions/1.9.3-p551/b...]
==> default: /home/vagrant/rroonga/vendor/bundle/ruby/1.9.1/gems/rake-compiler-0.9.5/lib/rake/extensiontask.rb:191:in `block (2 levels) in define_compile_tasks'
==> default: /home/vagrant/rroonga/vendor/bundle/ruby/1.9.1/gems/rake-compiler-0.9.5/lib/rake/extensiontask.rb:188:in `block in define_compile_tasks'
==> default: Tasks: TOP => native => native:x64-mingw32 => native:rroonga:x64-mingw32 => tmp/x64-mingw32/stage/lib/2.2/groonga.so => copy:groonga:x64-mingw32:2.2.1 => tmp/x64-mingw32/groonga/2.2.1/groonga.so => tmp/x64-mingw32/groonga/2.2.1/Makefile
==> default: (See full trace by running task with --trace)
==> default: + cp_pkg_gems
==> default: + mkdir -p /vagrant/pkg
==> default: + cp 'pkg/*.gem' /vagrant/pkg
==> default: cp: cannot stat ‘pkg/*.gem’: No such file or directory
```

**Comment by kenhys** [comment]
GRN_SCORER_ERRORに対応するPR
https://github.com/ranguba/rroonga/pull/58

**Comment by kenhys** [comment]
unregister pluginに対応するためのPR
https://github.com/ranguba/rroonga/pull/59

**Comment by kenhys** [comment]
分離した作業についてその階層がわかるようにコメントを更新。

**Comment by kou** [comment]
`Database#tables`は今の実装のままでもまぁいい。

scorerは次回リリース時に頑張る。（本当は別のチケットにわけておくべき。）
